ARG NODE_VERSION=22.13.1

# Create build stage
FROM node:${NODE_VERSION}

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Set environment variables
ENV HOST=0.0.0.0
ENV PORT=3000

# Expose the application port
EXPOSE $PORT

# Start the development server
CMD ["npm", "run", "dev"]
