repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=79"]
  # - repo: local
  #   hooks:
  #     - id: generate-api-schema
  #       name: Generate API Schema
  #       entry: bash -c "cd backend && python3 manage.py spectacular --file ../frontend/api-schema.yml && git add ../frontend/api-schema.yml"
  #       language: system
  #       pass_filenames: false
