services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/production/.env
 
  backend:
    build:
      context: .
      dockerfile: ./compose/production/backend/Dockerfile
    command: sh -c "until pg_isready -h db -p 5432; do sleep 1; done; python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 core.wsgi:application"
    depends_on:
      - db
    env_file:
      - .envs/production/.env
  frontend:
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
    depends_on:
      - backend
    env_file:
      - .envs/production/.env
volumes:
   postgres_data: