name: Django Tests

on:
  push:
    paths:
      - 'backend/*'
  pull_request:
    paths:
      - 'backend/*'

jobs:
  django-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -f backend/requirements.txt

      - name: Run django tests
        run: (cd backend && python3 manage.py test)

